name: MCSU_Refactored
description: mcsu?
version: 1.1.0
authors:
  - Cloud
  - Cak
main: com.cloud.mcsu_rf.MCSU_Main
api-version: 1.14
commands:
  listgames:
    description: Lists all loaded games (also tells you about any ones that are dying maybye)
    usage: /listGames
  playgame:
    description: plays specified game
    usage: /playGame <Gamename>
  givescore:
    description: gives score to team
    usage: /givescore <Team> <Scorecount>

  countdown:
    description: enable/dissable the countdown to MCSU
    usage: /countdown [stop/set] <End time hour> <End time minuite>

  tppoint:
    description: Creates a new tpPoint at the current position
    usage: /createpoint <Name>
  gamepoint:
    description: Creates a new debugTpPoint at the current position
    usage: /createdebugpoint <Name>
  goto:
    description: Goes to the specified tpPoint
    usage: /goto <tpPoint>
  team:
    description: Sets the player's team
    usage: /team set <Player Name> <TeamID>
  hub:
    description: Teleports you to the Hub,
    usage: /hub
  enablepvp:
    description: command to enable pvp,
    usage: /enablepvp

  blocksumoloot:
    description: testing command
    usage: /blocksumoloot