name: MCSU_Refactored
description: mcsu?
version: 4.1
authors:
  - Cloud
  - Cak
main: com.cloud.mcsu_rf.MCSU_Main
api-version: 1.14
commands:

  listgames:
    description: Lists all loaded games (also tells you about any ones that are dying maybye)
    usage: /listGames
  playgame:
    description: plays specified game
    usage: /playGame <Gamename>
  givescore:
    description: gives score to team
    usage: /givescore <Team> <Scorecount> <(optional) reason>
  clearscores:
    description: gives score to team
    usage: /givescore <Team> <Scorecount> <(optional) reason>
  forceendgame:
    description: resets current game
    usage: /forceendgame

  deveditmapmeta:
    description: -DEVTOOL- opens or creates map metadata for specified map or a list of all map meta
    usage: /deveditmapmeta <map>

  countdown:
    description: enable/dissable the countdown to MCSU
    usage: /countdown [stop/set] <End time hour> <End time minuite>

  tppoint:
    description: Creates a new tpPoint at the current position
    usage: /createpoint <Name>
  gamepoint:
    description: Creates a new debugTpPoint at the current position
    usage: /createdebugpoint <Name>
  goto:
    description: Goes to the specified tpPoint
    usage: /goto <tpPoint>
  mcsuteam:
    description: Sets the player's team
    usage: /mcsuteam set <Player Name> <TeamID>
  hub:
    description: Teleports you to the Hub,
    usage: /hub
  enablepvp:
    description: command to enable force pvp,
    usage: /enablepvp
  blocksumoloot:
    description: testing command
    usage: /blocksumoloot
  event:
    description: All of the MCSU event commands
    usage: /event <Action>
  mcsuevent:
    description: Starts an MCSU Event!
    usage: /mcsuevent
  winner:
    description: Crowns the winner of MCSU!
    usage: /winner
  stopglow:
    description: Stops players from glowing if a round of block sumo ended incorrectly
    usage: /stopglow
