name: MCSU_Refactored
version: 1.0.0
authors:
  - Cloud
  - Cak
main: com.cloud.mcsu_rf.MCSU_Main
api-version: 1.14
commands:
  listgames:
    description: Lists all loaded games (also tells you about any ones that are dying maybye)
    usage: /listGames
  playgame:
    description: plays specified game
    usage: /playGame <Gamename>
  MCSUscoreboard:
    description: Scoreboard Command
    usage: /playGame <Data>
  givescore:
    description: gives score to team - not functional rn
    usage: /givescore <Team> <Scorecount>
  countdown:
    description: enable/dissable the countdown to MCSU
    usage: /countdown <enable / dissable> <End time hour> <End time minuite>
  updatescoreboard:
    description: forces the scoreboard to update
    usage: /updatescoreboard
