name: MCSU_Refactored
version: 1.0.0
authors:
  - Cloud
  - Cak
main: com.cloud.mcsu_rf.MCSU_Main
api-version: 1.14
commands:
  listgames:
    description: Lists all loaded games (also tells you about any ones that are dying maybye)
    usage: /listGames
  playgame:
    description: Lists all loaded games (also tells you about any ones that are dying maybye)
    usage: /playGame <Gamename>
  MCSUscoreboard:
    description: Scoreboard Command
    usage: /playGame <Data>
  givescore:
    description: gives score to team
    usage: /givescore <Team> <Scorecount>
  setspawn:
    description: Edit the config using this command.
    usage: /setspawn <SpawnArea> <x> <y> <z>
  hub:
    description: Teleports the player to the hub.
    usage: /setspawn <SpawnArea> <x> <y> <z>